spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: MyAnimeList


  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true
    change-log: classpath:/db/changelog/changelog_master.yaml


logging:
  level:
    org.hibernate.sql: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
